#!/bin/bash


[ -z $ESHOP_FACTS ] && echo "Please run this script through oe-eshop-facts, e.g. ./oe-eshop-facts $0" && exit 1
. $ESHOP_FACT_BIN_PATH
. "$(dirname $BASH_SOURCE)/oe-eshop-edition_facts"

function main {
    execute_installation
}

function execute_installation {
    local LC_ESHOP_EDITION=`${ESHOP_PHP_BIN_PATH} -r "echo strtolower(\"${ESHOP_EDITION}\");"`
    local GET_DEMODATA_PATH="$ESHOP_OXID_VENDOR_PATH/oxideshop-demodata-${LC_ESHOP_EDITION}/src/out"

    cp -r $GET_DEMODATA_PATH "$ESHOP_SOURCE_PATH"
}

main
