services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\DemoDataInstaller\Framework\Module\Demodata\DemodataDaoInterface:
        class: OxidEsales\DemoDataInstaller\Framework\Module\Demodata\DemodataDao
        arguments:
            Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'
        public: true

    OxidEsales\DemoDataInstaller\Framework\Module\Demodata\DemodataCommand:
        class: OxidEsales\DemoDataInstaller\Framework\Module\Demodata\DemodataCommand
        tags:
            - { name: 'console.command', command: 'oe:setup:demodata' }
        public: true
